"use client";
import { useEffect,useState } from "react";
type UserRow={id:string;email:string;displayName:string;role:"admin"|"editor";createdAt:string;lastSignInAt:string};
export function UsersClient(){const [users,setUsers]=useState<UserRow[]>([]);const [message,setMessage]=useState("");const [loading,setLoading]=useState(true);
async function load(){setLoading(true);const r=await fetch("/api/admin/users");const d=await r.json().catch(()=>({}));setLoading(false);if(r.ok)setUsers(d.users||[]);else setMessage(d.message||"تعذر تحميل المستخدمين.");}
useEffect(()=>{void load();},[]);
async function invite(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const fd=new FormData(e.currentTarget);const r=await fetch("/api/admin/users",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email:fd.get("email"),displayName:fd.get("displayName"),role:fd.get("role")})});const d=await r.json().catch(()=>({}));if(!r.ok){setMessage(d.message||"تعذر إرسال الدعوة.");return;}setMessage("تم إرسال دعوة المستخدم عبر البريد.");e.currentTarget.reset();setTimeout(load,700);}
async function patch(id:string,body:Record<string,unknown>){const r=await fetch("/api/admin/users",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id,...body})});if(r.ok)load();else setMessage((await r.json().catch(()=>({}))).message||"تعذر التعديل.");}
async function remove(id:string){if(!confirm("حذف هذا المستخدم من Supabase Auth؟"))return;const r=await fetch("/api/admin/users",{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({id})});if(r.ok)load();else setMessage((await r.json().catch(()=>({}))).message||"تعذر الحذف.");}
return <div className="admin-stack"><form className="admin-card admin-inline-create" onSubmit={invite}><h2>دعوة مستخدم</h2><div className="admin-form-row three"><label>الاسم<input name="displayName" required/></label><label>البريد<input name="email" type="email" dir="ltr" required/></label><label>الصلاحية<select name="role"><option value="editor">محرر</option><option value="admin">مدير</option></select></label></div><button className="admin-primary-button">إرسال الدعوة</button>{message&&<p className="admin-message">{message}</p>}</form><section className="admin-card"><div className="admin-table-wrap"><table><thead><tr><th>المستخدم</th><th>البريد</th><th>الصلاحية</th><th>آخر دخول</th><th>إجراء</th></tr></thead><tbody>{users.map(u=><tr key={u.id}><td><input defaultValue={u.displayName} onBlur={e=>patch(u.id,{displayName:e.target.value})}/></td><td dir="ltr">{u.email}</td><td><select value={u.role} onChange={e=>patch(u.id,{role:e.target.value})}><option value="admin">مدير</option><option value="editor">محرر</option></select></td><td>{u.lastSignInAt?new Date(u.lastSignInAt).toLocaleString("ar"):"-"}</td><td><button className="danger" onClick={()=>remove(u.id)}>حذف</button></td></tr>)}{!loading&&!users.length&&<tr><td colSpan={5}>لا يوجد مستخدمون.</td></tr>}</tbody></table></div></section></div>;}
