import type { CmsContentSeed } from "./types";

const nowYear = "2026";

export const defaultContent: CmsContentSeed[] = [
  {
    type: "privacy",
    slug: "privacy-policy",
    titleAr: "سياسة الخصوصية",
    titleEn: "Privacy Policy",
    summaryAr: "نوضح كيف نتعامل مع بيانات التواصل التي يشاركها الزائر.",
    summaryEn: "How contact information shared by visitors is handled.",
    bodyAr: "قد نجمع الاسم والبريد الإلكتروني ورقم الهاتف وتفاصيل المشروع عند إرسال نموذج التواصل، وذلك للرد على الاستفسار ومناقشة الخدمة المطلوبة. لا نبيع بياناتك ولا نشاركها لأغراض تسويقية غير مرتبطة بطلبك.",
    bodyEn: "We may collect your name, email, phone number, and project details when you submit the contact form to respond and discuss the requested service. We do not sell your data or share it for unrelated marketing.",
    status: "published",
    sortOrder: 1
  },
  {
    type: "service",
    slug: "seo",
    titleAr: "تصدر نتائج البحث واسبق فيها",
    titleEn: "SEO",
    summaryAr: "تحسين محركات البحث لزيادة ظهور موقعك ومحتواك في نتائج البحث والوصول إلى العملاء المناسبين.",
    summaryEn: "I help improve visibility in search results with practical SEO foundations.",
    category: "Marketing",
    status: "published",
    sortOrder: 10,
    meta: { icon: "Search" }
  },
  {
    type: "service",
    slug: "website-development",
    titleAr: "مواقع ويب تخطف الأنظار فوراً",
    titleEn: "Website Development",
    summaryAr: "مواقع ويب احترافية وسريعة تمنح عملاءك تجربة سلسة وتعكس قوة علامتك الرقمية.",
    summaryEn: "I design and develop fast, clear websites that deliver a smooth client experience.",
    category: "Websites",
    status: "published",
    sortOrder: 20,
    meta: { icon: "Code2" }
  },
  {
    type: "service",
    slug: "branding",
    titleAr: "هوية بصرية ترسخ في الذاكرة",
    titleEn: "Visual Identity",
    summaryAr: "إنشاء تصاميم بصرية معبرة وجذابة لتعزيز التواصل مع جمهورك باحترافية.",
    summaryEn: "I create memorable visual identities and graphic design assets.",
    category: "Branding",
    status: "published",
    sortOrder: 30,
    meta: { icon: "Palette" }
  },
  {
    type: "service",
    slug: "digital-marketing",
    titleAr: "تسويق رقمي يترجم إلى نمو حقيقي",
    titleEn: "Digital Marketing",
    summaryAr: "تطبيق استراتيجيات مبتكرة عبر الإنترنت لزيادة الوعي بالعلامة التجارية وجذب العملاء.",
    summaryEn: "I build digital strategies that support awareness, acquisition, and growth.",
    category: "Marketing",
    status: "published",
    sortOrder: 40,
    meta: { icon: "Megaphone" }
  },
  {
    type: "service",
    slug: "social-media",
    titleAr: "إدارة منصات التواصل باحترافية",
    titleEn: "Social Media",
    summaryAr: "بناء حضور رقمي واستهداف دقيق للجمهور مع نمو مستمر للتفاعل.",
    summaryEn: "I manage social media and content systems that build engagement.",
    category: "Social Media",
    status: "published",
    sortOrder: 50,
    meta: { icon: "Share2" }
  },
  {
    type: "service",
    slug: "paid-advertising",
    titleAr: "إعلانات مدفوعة بعائد استثماري مرتفع",
    titleEn: "Paid Advertising",
    summaryAr: "إدارة الحملات الإعلانية باحترافية لرفع النتائج وتحسين العائد على الاستثمار.",
    summaryEn: "I plan, target, budget, and analyze campaigns to improve performance.",
    category: "Marketing",
    status: "published",
    sortOrder: 60,
    meta: { icon: "BarChart3" }
  },
  {
    type: "service",
    slug: "training",
    titleAr: "تدريب شخصي يطلق قدراتك الكامنة",
    titleEn: "Personal Training",
    summaryAr: "برامج تدريبية مخصصة لتطوير مهاراتك أو فريقك في التسويق والأعمال الرقمية.",
    summaryEn: "I provide personal training programs for your team and digital business skills.",
    category: "Training",
    status: "published",
    sortOrder: 70,
    meta: { icon: "GraduationCap" }
  },
  {
    type: "service",
    slug: "accounting-system",
    titleAr: "نظام محاسبة متكامل للشركات والأفراد",
    titleEn: "Accounting System",
    summaryAr: "حلول محاسبية منظمة تساعد الشركات والأفراد على إدارة أعمالهم بوضوح.",
    summaryEn: "I provide accounting system guidance for companies and individuals.",
    category: "Business",
    status: "published",
    sortOrder: 80,
    meta: { icon: "ReceiptText" }
  },
  {
    type: "service",
    slug: "trademark",
    titleAr: "تسجيل العلامات التجارية وحمايتها",
    titleEn: "Trademark Registration",
    summaryAr: "حماية علامتك التجارية قانونياً وضمان حقوقك في الأسواق المحلية والدولية.",
    summaryEn: "I support trademark registration and brand protection.",
    category: "Business",
    status: "published",
    sortOrder: 90,
    meta: { icon: "Tag" }
  },
  {
    type: "article",
    slug: "digital-community-strategies",
    titleAr: "استراتيجيات المجتمعات الرقمية",
    titleEn: "Digital Community Strategies",
    summaryAr: "كيف تعزز المجتمعات الحضور الرقمي والثقة والعلاقات طويلة المدى مع العلامة.",
    summaryEn: "How digital communities strengthen presence, trust, and long-term brand relationships.",
    bodyAr: "كيف تعزز المجتمعات الحضور الرقمي والثقة والعلاقات طويلة المدى مع العلامة.",
    bodyEn: "How digital communities strengthen presence, trust, and long-term brand relationships.",
    category: "التسويق الرقمي",
    status: "published",
    sortOrder: 10,
    meta: { date: "2025-03-23" }
  },
  {
    type: "article",
    slug: "international-trade-success-factors",
    titleAr: "عوامل نجاح التجارة الدولية في الحاضر والماضي",
    titleEn: "Factors for the Success of International Trade",
    summaryAr: "نظرة عملية إلى أساسيات التجارة وكيف تغير الأدوات الحديثة فرص التوسع الدولي.",
    summaryEn: "A practical look at trade fundamentals and how modern tools reshape international opportunities.",
    bodyAr: "نظرة عملية إلى أساسيات التجارة وكيف تغير الأدوات الحديثة فرص التوسع الدولي.",
    bodyEn: "A practical look at trade fundamentals and how modern tools reshape international opportunities.",
    category: "التجارة الدولية",
    status: "published",
    sortOrder: 20,
    meta: { date: "2025-03-23" }
  },
  {
    type: "article",
    slug: "network-marketing-reality",
    titleAr: "التسويق الشبكي بين الطموح والواقع",
    titleEn: "Network Marketing: Between Ambition and Reality",
    summaryAr: "قراءة متوازنة للوعود والمخاطر والتحديات العملية في التسويق الشبكي.",
    summaryEn: "A balanced discussion of promises, risks, and practical challenges around network marketing.",
    bodyAr: "قراءة متوازنة للوعود والمخاطر والتحديات العملية في التسويق الشبكي.",
    bodyEn: "A balanced discussion of promises, risks, and practical challenges around network marketing.",
    category: "الأعمال",
    status: "published",
    sortOrder: 30,
    meta: { date: "2025-03-21" }
  },
  {
    type: "project",
    slug: "digital-marketing-course",
    titleAr: "دورة التسويق الرقمي",
    titleEn: "Digital Marketing Course",
    summaryAr: "تعلم التسويق واصنع التأثير عبر برنامج تدريبي عملي ومنهجي.",
    summaryEn: "Learn marketing and create impact through a practical, structured course.",
    category: "Marketing",
    status: "published",
    sortOrder: 10,
    meta: { year: nowYear, client: "Training", services: ["Digital Marketing", "SEO", "AI"], image: "/images/legacy/digital-marketing-course.webp" }
  },
  {
    type: "project",
    slug: "graphic-design-course",
    titleAr: "دورة التصميم الجرافيكي",
    titleEn: "Graphic Design Course",
    summaryAr: "تعلم التصميم كمنظومة تفكير ومهارة مهنية من الأساسيات إلى المشاريع الحقيقية.",
    summaryEn: "Learn design as a professional skill from visual fundamentals to real projects.",
    category: "Branding",
    status: "published",
    sortOrder: 20,
    meta: { year: nowYear, client: "Training", services: ["Photoshop", "Illustrator", "Visual Identity"], image: "/images/legacy/graphic-design-course.webp" }
  },
  {
    type: "project",
    slug: "wordpress-course",
    titleAr: "دورة الوردبريس",
    titleEn: "WordPress Course",
    summaryAr: "تعلم بناء مواقع ووردبريس احترافية من الهيكلة والمحتوى إلى تحسين الظهور والنشر العملي.",
    summaryEn: "Build professional WordPress websites with structure, content, SEO, and practical publishing workflows.",
    category: "Websites",
    status: "published",
    sortOrder: 25,
    meta: { year: nowYear, client: "Training", services: ["WordPress", "Websites", "SEO"], image: "/images/legacy/wordpress-course.png" }
  },
  {
    type: "project",
    slug: "private-training",
    titleAr: "تدريب شخصي مصمم خصيصاً لك",
    titleEn: "Personal Training Designed for You",
    summaryAr: "جلسات تدريب فردية مصممة خصيصاً لتطوير مهاراتك وتحقيق أهدافك بثقة واحترافية.",
    summaryEn: "One-to-one sessions designed to develop your skills and reach your goals professionally.",
    category: "Business",
    status: "published",
    sortOrder: 30,
    meta: { year: nowYear, client: "Training", services: ["Training", "Marketing", "Business"], image: "/images/legacy/private-training-banner.png" }
  },
  {
    type: "integration",
    slug: "site-integrations",
    titleAr: "تكاملات الموقع",
    titleEn: "Site Integrations",
    summaryAr: "إدارة Google Search Console وGA4 وGTM وAdSense وBing Webmaster من لوحة التحكم.",
    summaryEn: "Manage Google Search Console, GA4, GTM, AdSense, and Bing Webmaster from the dashboard.",
    category: "System",
    status: "draft",
    sortOrder: 10,
    meta: {
      googleSearchConsoleEnabled: false,
      googleSiteVerification: "",
      ga4Enabled: false,
      ga4MeasurementId: "",
      gtmEnabled: false,
      gtmContainerId: "",
      adsenseEnabled: false,
      adsenseClientId: "",
      bingEnabled: false,
      bingVerification: ""
    }
  }
];

